//! CTAPHID framing state machine — the channel/transaction protocol
//! core (CTAP2.1 §11.2.5), generic over the fd layer so the fake-fd
//! tests drive it end-to-end.
//!
//! One [`Fsm`] owns one hidraw connection's channel state:
//!
//! - [`Fsm::allocate`] — CTAPHID_INIT on the broadcast CID
//!   (§11.2.9.1.3): 8-byte host nonce, echoed nonce matched, reserved
//!   CIDs rejected typed (§11.2.3);
//! - [`Fsm::resync`] — INIT on the ALLOCATED cid (§11.2.5.3): the
//!   abort-and-resynchronize escape hatch after any framing failure;
//! - [`Fsm::transaction`] — write a request and reassemble the
//!   response (§11.2.4): keepalives and ERROR frames are reported to
//!   the caller, foreign-CID packets are ignored (§11.2.3 concurrency
//!   model), spurious continuation packets ignored (§11.2.5.4
//!   mirror), SEQ violations typed;
//! - [`Fsm::send_cancel`] — CTAPHID_CANCEL (§11.2.9.1.5), reply not
//!   awaited, best-effort.
//!
//! Time discipline: every receive is sliced per the crate's
//! [`WAIT_SLICE`](crate::WAIT_SLICE) against the shared [`Deadline`]
//! (async-core D3/D4); nothing here sleeps on a real clock — the
//! [`Sleep`](fidoh_core::Sleep) factory drives all waiting.

use alloc::sync::Arc;
use alloc::vec::Vec;

use fidoh_core::{Deadline, Error, Phase, SleepHandle};

use crate::consts::{
    BROADCAST_CID, CMD_CBOR, CMD_ERROR, CMD_INIT, CMD_KEEPALIVE, CMD_PING, CMD_WINK,
    INIT_NONCE_LEN, INIT_RESPONSE_LEN, MAX_MESSAGE_SIZE,
};
use crate::error::{Capability, FramingError, HidError, HidErrorCode};
use crate::fd::RawFd;
use crate::packet;

/// The INIT handshake result (§11.2.9.1.3 response layout).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct InitInfo {
    /// The allocated channel id.
    pub cid: u32,
    /// CTAPHID protocol version identifier (2 for this protocol).
    pub protocol_version: u8,
    /// Device version major.minor.build (vendor-defined).
    pub device_version: [u8; 3],
    /// The capabilities byte, parsed (§11.2.9.1.3).
    pub capabilities: Capability,
    /// Raw capabilities byte (probes record it verbatim).
    pub capabilities_raw: u8,
}

impl InitInfo {
    /// Whether reserved capability bits were set (§11.2.9.1.3: MUST be
    /// zero from vendors) — a probeable device-quality signal.
    pub fn has_reserved_capability_bits(&self) -> bool {
        self.capabilities.reserved_bits() != 0
    }
}

/// A completed transaction's response frame.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Frame {
    /// A CTAPHID_CBOR response payload (CTAP2 status byte first, per
    /// the §11.2.9.1.2 message layout).
    Cbor(Vec<u8>),
    /// A PING echo (§11.2.9.1.1: the data sent is returned).
    Ping(Vec<u8>),
    /// A wink acknowledgement (§11.2.9.2.1: command echoed, BCNT 0).
    Wink,
}

/// A CTAPHID_ERROR reported by the device inside a transaction
/// (§11.2.9.1.6) — distinct from host-side framing errors.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TransactionOutcome {
    /// The transaction completed with this frame.
    Done(Frame),
    /// The device answered CTAPHID_ERROR with this code; not retried
    /// except ERR_CHANNEL_BUSY (handled inside the loop).
    DeviceError(HidErrorCode),
}

/// Outbound payload construction: CTAP command byte + encoded body
/// (the CTAPHID_CBOR message layout, §11.2.9.1.2).
pub fn cbor_payload(cmd_byte: u8, body: &[u8]) -> Vec<u8> {
    let mut p = Vec::with_capacity(body.len() + 1);
    p.push(cmd_byte);
    p.extend_from_slice(body);
    p
}

/// Errors the FSM folds into one type: HID-layer (framing/device/
/// capability/IO) or core-layer (deadline, device gone).
#[derive(Clone, Debug, PartialEq)]
pub enum FsmError {
    /// HID-layer failure.
    Hid(HidError),
    /// Core-layer failure (deadline/device taxonomy).
    Core(Error),
}

impl From<HidError> for FsmError {
    fn from(e: HidError) -> Self {
        Self::Hid(e)
    }
}

impl From<FramingError> for FsmError {
    fn from(e: FramingError) -> Self {
        Self::Hid(e.into())
    }
}

impl From<Error> for FsmError {
    fn from(e: Error) -> Self {
        Self::Core(e)
    }
}

impl FsmError {
    /// Strip to the async-core taxonomy.
    pub fn into_core(self) -> Error {
        match self {
            Self::Hid(e) => e.into_core(),
            Self::Core(e) => e,
        }
    }
}

/// Nonce generation for INIT (§11.2.9.1.3: 8 bytes "generated by the
/// host"). Counter-seeded: the nonce exists so the response can be
/// MATCHED (two hosts contending), and consecutive allocations within
/// one process must differ — an incrementing 64-bit counter satisfies
/// both without an entropy API; §11.2.9.1.3 requires only that the
/// host match the echo. `AtomicU64` (not `Cell`) so the `Fsm` — and
/// therefore every `Device` future — stays `Send` (async-core A4).
pub struct NonceSource {
    counter: core::sync::atomic::AtomicU64,
}

impl NonceSource {
    /// A nonce source starting at zero.
    pub fn new() -> Self {
        Self {
            counter: core::sync::atomic::AtomicU64::new(0),
        }
    }

    /// The next nonce.
    pub fn next(&self) -> [u8; INIT_NONCE_LEN] {
        use core::sync::atomic::Ordering;
        let n = self.counter.fetch_add(1, Ordering::Relaxed).wrapping_add(1);
        n.to_be_bytes()
    }
}

impl Default for NonceSource {
    fn default() -> Self {
        Self::new()
    }
}

/// Transaction-loop failures that are not frame completion.
enum LoopFailure {
    /// ERR_CHANNEL_BUSY — bounded retry (§11.2.9.1.6).
    Busy,
    /// Everything else.
    Fatal(FsmError),
}

/// One-step outcome inside the receive loop.
enum Step {
    /// Keep consuming reports.
    Continue,
    /// The frame (or a device error) resolved the transaction.
    Done(TransactionOutcome),
    /// The device is busy for our channel: re-issue.
    Busy,
}

/// Message reassembly state (§11.2.4): expects an initialization
/// packet then ascending-SEQ continuation packets on exactly one cid.
pub struct Assembler {
    cid: u32,
    /// Total announced payload length (BCNT).
    bcnt: usize,
    /// Payload bytes so far.
    payload: Vec<u8>,
    /// Next expected continuation SEQ.
    next_seq: u8,
    /// A message is in progress.
    active: bool,
}

impl Assembler {
    /// An idle assembler for one channel.
    pub fn new(cid: u32) -> Self {
        Self {
            cid,
            bcnt: 0,
            payload: Vec::new(),
            next_seq: 0,
            active: false,
        }
    }

    /// Begin a message from an initialization packet's header + full
    /// report.
    pub fn begin(&mut self, hdr: packet::InitHeader, report: &[u8]) -> Result<(), FsmError> {
        if hdr.bcnt > MAX_MESSAGE_SIZE {
            return Err(FramingError::LengthBeyondMaximum { bcnt: hdr.bcnt }.into());
        }
        self.bcnt = hdr.bcnt;
        self.payload.clear();
        self.payload
            .extend_from_slice(&report[packet::INIT_HEADER_OFF..]);
        self.next_seq = 0;
        self.active = true;
        Ok(())
    }

    /// Append a continuation packet, enforcing SEQ (§11.2.4); a
    /// spurious continuation with no message in progress is ignored
    /// (§11.2.5.4 rule mirrored host-side, spec scenario).
    pub fn push_continuation(&mut self, seq: u8, report: &[u8]) -> Result<(), FsmError> {
        if !self.active {
            return Ok(());
        }
        if seq != self.next_seq {
            return Err(FramingError::InvalidSeq {
                cid: self.cid,
                got: seq,
                expected: self.next_seq,
            }
            .into());
        }
        self.next_seq += 1;
        self.payload
            .extend_from_slice(&report[packet::CONT_HEADER_OFF..]);
        if self.payload.len() > self.bcnt.max(MAX_MESSAGE_SIZE) {
            return Err(FramingError::LengthMismatch {
                expected: self.bcnt,
                got: self.payload.len(),
            }
            .into());
        }
        Ok(())
    }

    /// Whether the announced length has been fully received.
    pub fn complete(&self) -> bool {
        self.active && self.payload.len() >= self.bcnt
    }

    /// Truncate to BCNT and return the payload (§11.2.4: bytes beyond
    /// BCNT in the final packet are zero padding).
    pub fn finish(&mut self) -> Vec<u8> {
        self.payload.truncate(self.bcnt);
        self.active = false;
        core::mem::take(&mut self.payload)
    }
}

/// Decode the 17-byte INIT response layout (§11.2.9.1.3):
/// nonce(8) cid(4) version(1) dev-version(3) capabilities(1).
/// Longer payloads are accepted for forward compatibility (§11.2.9.1.3
/// note); the caller has already matched the echoed nonce (bytes 0–8).
pub fn decode_init_response(payload: &[u8]) -> Result<InitInfo, FsmError> {
    if payload.len() < INIT_RESPONSE_LEN {
        return Err(FramingError::InitResponseShort { got: payload.len() }.into());
    }
    let cid = u32::from_be_bytes([payload[8], payload[9], payload[10], payload[11]]);
    Ok(InitInfo {
        cid,
        protocol_version: payload[12],
        device_version: [payload[13], payload[14], payload[15]],
        capabilities: Capability(payload[16]),
        capabilities_raw: payload[16],
    })
}

/// One hidraw connection's CTAPHID state machine over an fd.
pub struct Fsm<F: RawFd> {
    fd: F,
    /// The allocated channel id; `None` until a successful INIT.
    cid: Option<u32>,
    /// The last successful INIT's info.
    info: Option<InitInfo>,
    /// Nonce generator (deterministic; injectable via `with_nonce`).
    nonce: Arc<NonceSource>,
}

impl<F: RawFd> Fsm<F> {
    /// Bind the FSM to an fd. The channel is unallocated until
    /// [`Fsm::allocate`] succeeds.
    pub fn new(fd: F) -> Self {
        Self {
            fd,
            cid: None,
            info: None,
            nonce: Arc::new(NonceSource::new()),
        }
    }

    /// The allocated channel id, if any.
    pub fn cid(&self) -> Option<u32> {
        self.cid
    }

    /// The parsed INIT info of the last successful allocation.
    pub fn init_info(&self) -> Option<InitInfo> {
        self.info
    }

    /// CTAPHID_INIT on the broadcast CID (§11.2.9.1.3): allocate a
    /// channel. Bounded by the remaining budget (the caller names the
    /// phase: `Connect` at connect, `ChannelOpen` on re-handshake).
    pub async fn allocate(
        &mut self,
        deadline: &Deadline,
        sleep: SleepHandle<'_>,
    ) -> Result<InitInfo, FsmError> {
        let info = self.init_handshake(BROADCAST_CID, deadline, sleep).await?;
        // §11.2.3: channel 0 and 0xFFFFFFFF are reserved.
        if info.cid == 0 || info.cid == BROADCAST_CID {
            return Err(FramingError::ReservedCid { cid: info.cid }.into());
        }
        self.cid = Some(info.cid);
        self.info = Some(info);
        Ok(info)
    }

    /// INIT on the ALLOCATED cid (§11.2.5.3): the device discards the
    /// channel's transaction/buffer state and readies it for a new
    /// transaction. Never allocated → this IS allocation.
    pub async fn resync(
        &mut self,
        deadline: &Deadline,
        sleep: SleepHandle<'_>,
    ) -> Result<InitInfo, FsmError> {
        match self.cid {
            None => self.allocate(deadline, sleep).await,
            Some(cid) => self.init_handshake(cid, deadline, sleep).await,
        }
    }

    /// One INIT exchange on `on_cid` with a fresh nonce (§11.2.9.1.3).
    async fn init_handshake(
        &mut self,
        on_cid: u32,
        deadline: &Deadline,
        sleep: SleepHandle<'_>,
    ) -> Result<InitInfo, FsmError> {
        let nonce = self.nonce.next();
        let packets = packet::encode_message(on_cid, CMD_INIT, &nonce)?;
        for p in &packets {
            self.fd.write_report(p).map_err(FsmError::Hid)?;
        }
        loop {
            let report =
                fd_wait::read_report_bounded(&mut self.fd, deadline, sleep, Phase::ChannelOpen)
                    .await?;
            let hdr = packet::parse_init_header(&report)?;
            // The INIT reply is addressed to the cid we sent (the
            // broadcast cid on allocation, the channel cid on resync);
            // packets on other channels are other clients' traffic and
            // ignored (§11.2.3).
            if hdr.cid != on_cid || hdr.cmd != CMD_INIT {
                continue;
            }
            let mut payload = Vec::new();
            payload.extend_from_slice(&report[packet::INIT_HEADER_OFF..]);
            // INIT fits one packet (BCNT ≤ 17 ≤ 57); BCNT beyond that
            // would be a forward-compat longer response — still single
            // packet by §11.2.9.1.3, truncated to BCNT.
            if payload.len() > hdr.bcnt {
                payload.truncate(hdr.bcnt);
            }
            if payload.len() < INIT_NONCE_LEN || payload[..INIT_NONCE_LEN] != nonce {
                return Err(FramingError::NonceMismatch.into());
            }
            return decode_init_response(&payload);
        }
    }

    /// CTAPHID_CANCEL (§11.2.9.1.5): abort the pending transaction on
    /// the channel. One packet, no reply awaited (the authenticator
    /// MUST NOT reply to the cancel itself). An unallocated channel
    /// has nothing to cancel: Ok.
    pub fn send_cancel(&mut self) -> Result<(), HidError> {
        let Some(cid) = self.cid else {
            return Ok(());
        };
        let packets = packet::encode_message(cid, crate::consts::CMD_CANCEL, &[])?;
        // Standalone single-packet command; the write is the whole
        // send (§11.2.9.1.5). Write failure is the caller's
        // best-effort decision (async-core OQ-3).
        self.fd.write_report(&packets[0])
    }

    /// Whether a CTAP command can run: CAPABILITY_CBOR must be
    /// advertised (design D6) and a channel must exist.
    pub fn ensure_cbor_ready(&self) -> Result<(), FsmError> {
        match self.info {
            Some(info) if info.capabilities.cbor() => Ok(()),
            Some(_) => Err(HidError::NoCbor.into()),
            None => Err(HidError::NoCbor.into()),
        }
    }

    /// Run one CTAPHID_CBOR (or PING/WINK) transaction (§11.2.5.1):
    /// write the request (pre-validated ≤
    /// [`MAX_MESSAGE_SIZE`](crate::consts::MAX_MESSAGE_SIZE)), then
    /// reassemble the response, surfacing every keepalive status
    /// through `on_keepalive` (§11.2.9.1.7 — surfaced, never
    /// swallowed).
    ///
    /// Busy handling: ERR_CHANNEL_BUSY triggers a budget-bounded
    /// Sleep-driven delay, then the FULL request re-issue
    /// (§11.2.9.1.6 client-SHOULD-retry); expiry is the typed
    /// `Timeout(phase)`.
    ///
    /// `phase` names deadline expiry for the wait (the command's
    /// phase, or `UserPresence` once UP_NEEDED was seen — the caller
    /// picks, mirroring the ceremony's phase-renaming rule).
    pub async fn transaction(
        &mut self,
        cmd: u8,
        payload: &[u8],
        phase: Phase,
        deadline: &Deadline,
        sleep: SleepHandle<'_>,
        mut on_keepalive: impl FnMut(u8) + Send,
    ) -> Result<TransactionOutcome, FsmError> {
        let Some(cid) = self.cid else {
            return Err(FramingError::UnexpectedCommand {
                got: cmd,
                expected: CMD_CBOR,
            }
            .into());
        };
        loop {
            let packets = packet::encode_message(cid, cmd, payload)?;
            for p in &packets {
                self.fd.write_report(p).map_err(FsmError::Hid)?;
            }
            match self
                .receive_loop(cid, cmd, phase, deadline, sleep, &mut on_keepalive)
                .await
            {
                Ok(outcome) => return Ok(outcome),
                Err(LoopFailure::Busy) => {
                    // Short Sleep-driven delay, then re-issue at the
                    // loop head. Budget-bounded via consume_slice;
                    // exhaustion is the typed timeout naming the
                    // busy-retry's phase.
                    let Some(granted) = deadline.consume_slice(crate::BUSY_RETRY_DELAY) else {
                        return Err(Error::Timeout(phase).into());
                    };
                    sleep.sleep(granted).await;
                }
                Err(LoopFailure::Fatal(e)) => return Err(e),
            }
        }
    }

    /// The receive loop of one transaction attempt (§11.2.4/§11.2.5.4).
    async fn receive_loop(
        &mut self,
        cid: u32,
        expect_cmd: u8,
        phase: Phase,
        deadline: &Deadline,
        sleep: SleepHandle<'_>,
        on_keepalive: &mut (dyn FnMut(u8) + Send),
    ) -> Result<TransactionOutcome, LoopFailure> {
        let mut assembler = Assembler::new(cid);
        loop {
            let report = fd_wait::read_report_bounded(&mut self.fd, deadline, sleep, phase)
                .await
                .map_err(FsmError::Core)
                .map_err(LoopFailure::Fatal)?;
            match Self::step(&mut assembler, expect_cmd, &report, on_keepalive)
                .map_err(LoopFailure::Fatal)?
            {
                Step::Continue => {}
                Step::Done(outcome) => return Ok(outcome),
                Step::Busy => return Err(LoopFailure::Busy),
            }
            // The gap before the NEXT packet is bounded by the same
            // deadline through the next read slice; expiry there is
            // the typed timeout naming the caller's phase (reassembly
            // included — §11.2.5.2 fixes no numeric gap bound, design
            // OQ-1).
        }
    }

    /// Fold one inbound report into the assembler.
    fn step(
        assembler: &mut Assembler,
        expect_cmd: u8,
        report: &[u8],
        on_keepalive: &mut dyn FnMut(u8),
    ) -> Result<Step, FsmError> {
        match packet::classify(report)? {
            packet::InboundKind::Init => {
                let hdr = packet::parse_init_header(report)?;
                if hdr.cid != assembler.cid {
                    // Foreign channel: other clients' traffic (§11.2.3),
                    // ignored without disturbing the transaction.
                    return Ok(Step::Continue);
                }
                match hdr.cmd {
                    CMD_KEEPALIVE => {
                        let payload = packet::payload_of(report, hdr)?;
                        if payload.len() != 1 {
                            return Err(FramingError::UnexpectedBcnt {
                                cmd: CMD_KEEPALIVE,
                                got: payload.len(),
                            }
                            .into());
                        }
                        // §11.2.9.1.7: a keepalive is never a response
                        // and never ends the transaction; every status
                        // surfaces (unknown statuses are
                        // processing-class progress).
                        on_keepalive(payload[0]);
                        Ok(Step::Continue)
                    }
                    CMD_ERROR => {
                        let payload = packet::payload_of(report, hdr)?;
                        if payload.len() != 1 {
                            return Err(FramingError::UnexpectedBcnt {
                                cmd: CMD_ERROR,
                                got: payload.len(),
                            }
                            .into());
                        }
                        let code = HidErrorCode::from_u8(payload[0]);
                        if code.is_channel_busy() {
                            return Ok(Step::Busy);
                        }
                        Ok(Step::Done(TransactionOutcome::DeviceError(code)))
                    }
                    c if c == expect_cmd => {
                        assembler.begin(hdr, report)?;
                        // A single-packet message (BCNT ≤ 57) is
                        // already complete here — §11.2.4: "A message
                        // with payload ≤ 57 bytes fits one packet."
                        if assembler.complete() {
                            let payload = assembler.finish();
                            let frame = match expect_cmd {
                                CMD_PING => Frame::Ping(payload),
                                CMD_WINK => Frame::Wink,
                                _ => Frame::Cbor(payload),
                            };
                            Ok(Step::Done(TransactionOutcome::Done(frame)))
                        } else {
                            Ok(Step::Continue)
                        }
                    }
                    // A frame on our channel answering a different
                    // command: ERR_INVALID_CMD-class (§11.2.9.1.6).
                    got => Err(FramingError::UnexpectedCommand {
                        got,
                        expected: expect_cmd,
                    }
                    .into()),
                }
            }
            packet::InboundKind::Continuation => {
                let (pcid, seq) = packet::parse_cont_header(report)?;
                if pcid != assembler.cid {
                    return Ok(Step::Continue); // foreign traffic
                }
                assembler.push_continuation(seq, report)?;
                if assembler.complete() {
                    let payload = assembler.finish();
                    let frame = match expect_cmd {
                        CMD_PING => Frame::Ping(payload),
                        CMD_WINK => Frame::Wink,
                        _ => Frame::Cbor(payload),
                    };
                    Ok(Step::Done(TransactionOutcome::Done(frame)))
                } else {
                    Ok(Step::Continue)
                }
            }
        }
    }
}

use crate::fd_wait;
