//! Conformance-vector provenance tests (testing-strategy spec
//! requirement "Conformance vector provenance", scenario "Spec-derived
//! vectors round-trip the canonical encoder").
//!
//! Every file in `vectors/spec-derived/` is decoded with fidoh-core's
//! strict CBOR decoder and re-encoded; the re-encoded bytes must be
//! byte-identical to the committed vector. Vectors transcribed directly
//! from the CTAP2.1 specification's own examples are ground truth for
//! the canonical encoder (never captured from a third-party
//! authenticator — cleanroom rule); `vectors/constructed/` fixtures are
//! generated by the `generate_vectors` example and verified for
//! regeneration by CI (`.github/workflows/vectors.yml`).
//!
//! The manifest (`vectors/manifest.json`) is also validated: every
//! committed vector file must be labeled with its source kind
//! (`spec-derived` | `constructed`) and provenance.

use std::path::{Path, PathBuf};

use fidoh_core::cbor::CborValue;
use fidoh_core::error::DecodePolicy;

/// Repo root (this test lives at `<root>/crates/fidoh-core/tests/`).
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// Hex parsing, hand-rolled: fidoh-core's `[dependencies]` stays empty
/// (design D5), and dev-dependencies must not grow either.
fn hex_decode(s: &str) -> Result<Vec<u8>, String> {
    let s = s.trim();
    let bytes = s.as_bytes();
    if bytes.len() % 2 != 0 {
        return Err(format!("odd hex length {}", bytes.len()));
    }
    let mut out = Vec::with_capacity(bytes.len() / 2);
    for pair in bytes.chunks(2) {
        let hi = (pair[0] as char).to_digit(16).ok_or("bad hex digit")?;
        let lo = (pair[1] as char).to_digit(16).ok_or("bad hex digit")?;
        out.push(((hi << 4) | lo) as u8);
    }
    Ok(out)
}

/// Every `*.hex` file under `vectors/spec-derived/` paired with its
/// manifest entry.
fn spec_derived_vectors() -> Vec<(VectorEntry, Vec<u8>)> {
    let manifest: Vec<VectorEntry> = manifest_entries()
        .into_iter()
        .filter(|e| e.kind == "spec-derived")
        .collect();
    let dir = repo_root().join("vectors").join("spec-derived");
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".hex"))
        .collect();
    names.sort();
    names
        .into_iter()
        .map(|name| {
            let entry = manifest
                .iter()
                .find(|e| e.file.ends_with(&name))
                .unwrap_or_else(|| panic!("{name}: not labeled in vectors/manifest.json"));
            let path = dir.join(&name);
            let text = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
            let bytes = hex_decode(&text).unwrap_or_else(|e| panic!("{name}: {e}"));
            (
                VectorEntry {
                    file: name,
                    kind: entry.kind.clone(),
                    framed: entry.framed,
                },
                bytes,
            )
        })
        .collect()
}

/// One manifest vector entry: file name, source kind, and whether the
/// file carries a leading transport byte (command byte or response
/// status byte) before the CBOR payload.
struct VectorEntry {
    file: String,
    kind: String,
    framed: bool,
}

/// Strip the leading transport byte on framed vectors (the manifest's
/// `framing` field drives this: "leading ..." means byte 0 is framing).
fn cbor_payload<'a>(entry: &VectorEntry, bytes: &'a [u8]) -> Result<&'a [u8], String> {
    if entry.framed {
        let (_, rest) = bytes
            .split_first()
            .ok_or_else(|| "empty framed vector".to_string())?;
        Ok(rest)
    } else {
        Ok(bytes)
    }
}

/// Scenario: each spec-derived vector's CBOR payload decodes, and the
/// canonical re-encoding of the decoded value is byte-identical to the
/// committed bytes.
///
/// Canonical-strictness policy (core-model's): three of the four
/// spec-derived vectors are fully canonical — strict decode succeeds
/// and the canonical form is unique, so strict re-encoding reproduces
/// the committed bytes exactly. The §11.3.6 response vector is the
/// spec's own published bytes and encodes authData's length in a
/// uint16 form (0x59 0x00 a2) where the minimal form is 0x58 A2:
/// transcribed faithfully, it surfaces the spec's encoding-form
/// deviation as the TYPED strict error `NonCanonicalEncoding`
/// (core-model's strictness policy applied to the spec's own bytes),
/// and its value fidelity is proven by tolerant decode + canonical
/// re-encode (673 canonical bytes replacing the one non-minimal head).
#[test]
fn spec_derived_vectors_round_trip_through_strict_decoder() {
    for (entry, bytes) in spec_derived_vectors() {
        let name = entry.file.as_str();
        let payload = cbor_payload(&entry, &bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        // Value fidelity: the decoded value re-encodes to the CANONICAL
        // serialization of the same structure, which for every vector
        // except the deliberately non-minimal §11.3.6 response IS the
        // committed bytes.
        let value = CborValue::decode(payload, DecodePolicy::Tolerant)
            .unwrap_or_else(|e| panic!("{name}: tolerant decode failed: {e}"));
        let canonical = value
            .encode()
            .unwrap_or_else(|e| panic!("{name}: re-encode failed: {e}"));
        if name.starts_with("makecredential-response--") {
            // The spec's own non-minimal length head is the only delta;
            // everything else about the re-encode must be identical.
            assert_eq!(payload.len(), canonical.len() + 1);
            assert_eq!(payload[0], 0xA3);
            assert_eq!(canonical[0], 0xA3);
            assert_eq!(payload[1], 0x01);
            assert_eq!(canonical[1], 0x01);
            // Payload layout: 0xA3 01 66 "packed" 02 <len head> A2…
            // ("packed" spans offsets 3..9, so the authData bstr head
            // sits at offsets 9..12; the canonical re-encode stores it
            // in the minimal 0x58 form, shifting everything after by 1).
            assert_eq!(&payload[9..12], &[0x02, 0x59, 0x00][..]);
            assert_eq!(&canonical[9..11], &[0x02, 0x58][..]);
            assert_eq!(&payload[12..], &canonical[11..]);
            // Typed strict posture: the deviation is a
            // NonCanonicalEncoding, not a structural failure.
            let strict = CborValue::decode(payload, DecodePolicy::Strict);
            assert!(
                matches!(
                    strict,
                    Err(fidoh_core::error::DecodeError::NonCanonicalEncoding { .. })
                ),
                "{name}: expected the spec's non-minimal length form to be a typed strict error"
            );
        } else {
            assert_eq!(
                canonical, payload,
                "{name}: canonical re-encode differs from the spec's bytes"
            );
            assert!(
                CborValue::decode(payload, DecodePolicy::Strict).is_ok(),
                "{name}: canonical spec bytes must strict-decode"
            );
        }
    }
}

/// Scenario: spec-derived vectors are also valid under the tolerant
/// posture (canonical form is a subset of tolerant input).
#[test]
fn spec_derived_vectors_decode_tolerantly() {
    for (entry, bytes) in spec_derived_vectors() {
        let name = entry.file.as_str();
        let payload = cbor_payload(&entry, &bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(
            CborValue::decode(payload, DecodePolicy::Tolerant).is_ok(),
            "{name}: must decode under the tolerant posture"
        );
    }
}

/// The manifest labels every vector file; parse it without serde
/// (fidoh-core has no dependencies) into (file, kind) pairs.
fn manifest_entries() -> Vec<VectorEntry> {
    let path = repo_root().join("vectors").join("manifest.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let mut entries: Vec<VectorEntry> = Vec::new();
    let mut pending_file: Option<String> = None;
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("\"file\": \"") {
            pending_file = rest.strip_suffix("\",").map(String::from);
        } else if let Some(rest) = line.strip_prefix("\"source\": \"") {
            let kind = rest.strip_suffix("\",").or_else(|| rest.strip_suffix("\""));
            if let (Some(file), Some(kind)) = (pending_file.take(), kind) {
                entries.push(VectorEntry {
                    file,
                    kind: String::from(kind),
                    framed: false,
                });
            }
        } else if let Some(rest) = line.strip_prefix("\"framing\": \"") {
            // "leading ..." => the first byte is transport framing.
            if let Some(entry) = entries.last_mut() {
                entry.framed = rest.starts_with("leading");
            }
        }
    }
    assert!(
        !entries.is_empty(),
        "manifest at {} labeled no vectors",
        path.display()
    );
    entries
}

/// Every committed vector file is labeled with its source kind, and the
/// constructed vectors are labeled `constructed` (never `captured` —
/// cleanroom rule: no third-party-authenticator vectors).
#[test]
fn manifest_labels_every_vector_file() {
    let vectors_dir = repo_root().join("vectors");
    let entries = manifest_entries();
    let mut labeled: Vec<String> = entries.iter().map(|e| e.file.clone()).collect();
    labeled.sort();

    let mut on_disk: Vec<String> = Vec::new();
    for sub in ["spec-derived", "constructed"] {
        let dir = vectors_dir.join(sub);
        let found: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .filter(|name| name != "manifest.json")
            .collect();
        on_disk.extend(found.into_iter().map(|name| format!("{sub}/{name}")));
    }
    on_disk.sort();

    assert_eq!(
        labeled, on_disk,
        "manifest labels must match the committed vector files exactly"
    );

    for entry in entries {
        let file = entry.file.as_str();
        let kind = entry.kind.as_str();
        assert!(
            kind == "spec-derived" || kind == "constructed",
            "{file}: unknown source kind {kind:?} (expected spec-derived | constructed)"
        );
        assert!(
            kind == file.split('/').next().unwrap_or(""),
            "{file}: source kind {kind:?} disagrees with its directory"
        );
    }
}

/// Constructed vectors exist and are valid JSON snapshots with the
/// canonical member shape (regenerability itself is asserted in CI by
/// `.github/workflows/vectors.yml` via `diff -r`; this test pins that
/// the committed set is present and shaped).
#[test]
fn constructed_vectors_are_committed_snapshot_json() {
    let dir = repo_root().join("vectors").join("constructed");
    let names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".json"))
        .collect();
    assert!(
        !names.is_empty(),
        "no constructed vectors committed under {}",
        dir.display()
    );
    for name in names {
        let path = dir.join(&name);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        for member in ["\"version\": 1", "\"sign_count\":", "\"credentials\":"] {
            assert!(
                text.contains(member),
                "{name}: snapshot JSON missing {member}"
            );
        }
        assert!(
            !text.contains("\"captured\""),
            "{name}: constructed vector must never be labeled captured"
        );
    }
}
